// frontend/src/App.vue
<template>
  <v-app>
    <v-main>
      <v-container>
      <login/> <br/>
      <home/> <br/>
      <create-task/> <br/>
      <list-tasks/> <br/>
      <admin-dashboard/> <br/>
      <add-user/> <br/>
      </v-container>
    </v-main>
  </v-app>
</template>

<script lang="ts">
import Vue from 'vue';
import login from './components/login.vue';
import home from './components/home.vue';
import createTask from './components/create-task.vue';
import listTasks from './components/listTasks.vue';
import adminDashboard from './components/admin-dashboard.vue';
import addUser from './components/add-user.vue';

export default Vue.extend({
  name: 'App',

  components: {
    login,
    home,
    createTask,
    listTasks,
    adminDashboard,
    addUser
  },

  data: () => ({
    //
  }),
});
</script>

// frontend/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'] 
})
export class AppComponent {
  title = 'manytasks';
}


<app-site-heading></app-site-heading>
<div class="container">

  <frontend-app>Loading...</frontend-app>
  <app-home></app-home>
  <app-create-task></app-create-task>
  <app-task-list></app-task-list>

  <app-admin-dashboard></app-admin-dashboard>
  <app-admin-create-user></app-admin-create-user>
</div>
